export const auraReykjavikPositions = [
  {
    question: "Resident Artist",
    answer:
      "Join Our Team at Aura Reykjavik!\n\nAre you an artist looking for a unique opportunity to join a creative, close-knit team?\n\nAura, located in the heart of Reykjavik, is searching for a talented Resident Artist to join our calm studio. At Aura, we take pride in being more than just a tattoo studio. We are a community that nurtures artists who have or are developing their own distinctive style. For us, artistry comes first. Many of our current team members are also involved in other creative fields, creating a dynamic and inspiring atmosphere.\n\nWe're excited to offer a position for someone who shares our passion for creativity. Starting with three days per week, the role operates on a standard percentage basis. After a successful probationary period, there's an option to transition to a fixed monthly rent – tailored to suit you and the studio.\n\nWhat We Provide:\n\n• As eco-friendly as possible disposables to support a sustainable workspace.\n\n• A fully equipped studio with drawing area, multiple printers, and tea/coffee facilities.\n\n• Opportunities to participate in workshops and events (previously, these have included a chamber concert given by Ovors and Tomasz Mreńca , Thai massage workshop, Tibetan bowls sound massage played by wellsprings.is).\n\nWhat We're Looking For:\n\n• Experience: 2+ years of tattooing, including at least 1 year in a credible tattoo studio.\n\n• Style: A distinctive artistic approach that reflects your creative vision.\n\n• Professionalism: High standards and attention to detail.\n\n• Team Spirit: A collaborative attitude, ready to contribute to a fun, supportive team environment.\n\nThis is not a position for someone who just wants to clock in and clock out.\n\nHow to Apply:\n\nPlease email hello@aurareykjavik.com with:\n\n1. A cover letter (as a .doc or .pdf) introducing yourself, your inspirations, ambitions, and why you'd love to work with us.\n\n2. A portfolio of your current tattoo work (Instagram, website, or PDF).\n\n3. A portfolio of your future artistic direction – sketches, mock-ups, or inspiration images. We want to see where your creativity is heading, even if it's different from your current work.\n\nThis is your chance to become part of a studio that values artistry, individuality, and community. We can't wait to see your work and hear your story!\n\nAura Reykjavik – a home for artists.",
  },
  {
    question: "Guest Spot Artist",
    answer:
      "Want to GUEST AT AURA?\n\nWe would love to hear from you! We love having guests and are always open to new artists!\n\nThe best way to get in touch about guesting is to send an e-mail to :\n\nhello@aurareykjavik.com ♡",
  },
];
